# Generated by Django 5.2.12 on 2026-03-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cibil_score',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='customer',
            name='delay_weight',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='customer',
            name='inactivity_weight',
            field=models.FloatField(default=2.0),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_order_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
