# Generated by Django 5.2.12 on 2026-03-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0002_customer_cibil_score_customer_delay_weight_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='cibil_score',
            new_name='cibil_score_v1',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='delay_weight',
            new_name='delay_weight_v1',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='inactivity_weight',
            new_name='inactivity_weight_v1',
        ),
        migrations.AddField(
            model_name='customer',
            name='average_limit',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='customer',
            name='cibil_score_v2',
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name='customer',
            name='gold_limit',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='customer',
            name='v2_decay_penalty_mult',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='customer',
            name='v2_decay_start_days',
            field=models.IntegerField(default=90),
        ),
        migrations.AddField(
            model_name='customer',
            name='v2_delay_penalty_mult',
            field=models.FloatField(default=10.0),
        ),
        migrations.AddField(
            model_name='customer',
            name='v2_volume_boost_mult',
            field=models.FloatField(default=25.0),
        ),
    ]
