# Generated by Django 5.2.12 on 2026-03-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0003_rename_cibil_score_customer_cibil_score_v1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='v2_volume_percentile',
            field=models.FloatField(default=0.5),
        ),
    ]
