# Generated by Django 5.2.12 on 2026-05-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0004_customer_v2_volume_percentile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_sheet_url', models.URLField(blank=True, help_text='Public URL to the Google Sheet (Anyone with the link can view)', max_length=500, null=True)),
            ],
        ),
    ]
