# Generated by Django 5.2.12 on 2026-07-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0006_payment_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='invoice_google_sheet_url',
            field=models.URLField(blank=True, help_text='Public URL to the Invoices Google Sheet (Anyone with the link can view)', max_length=500, null=True, verbose_name='Invoices Google Sheet URL'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='delay_weight_v1',
            field=models.FloatField(default=20.0),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='google_sheet_url',
            field=models.URLField(blank=True, help_text='Public URL to the Payments Google Sheet (Anyone with the link can view)', max_length=500, null=True, verbose_name='Payments Google Sheet URL'),
        ),
    ]
