# Generated by Django 5.2.12 on 2026-07-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0007_systemsettings_invoice_google_sheet_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='delay_bucket_thresholds',
            field=models.CharField(default='5, 15, 30, 60', help_text='Comma-separated list of days for delay buckets. Example: 5, 15, 30, 60', max_length=100, verbose_name='Delay Bucket Thresholds'),
        ),
    ]
