# Generated by Django 5.2.12 on 2026-07-20 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0008_systemsettings_delay_bucket_thresholds'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='customer_delay_thresholds',
            field=models.CharField(default='5, 15, 30, 60', help_text='Comma-separated list of days for customer average delay buckets.', max_length=100, verbose_name='Customer Average Delay Bucket Thresholds'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='payment_delay_thresholds',
            field=models.CharField(default='5, 15, 30, 60', help_text='Comma-separated list of days for payment completion delay buckets.', max_length=100, verbose_name='Payment Completion Delay Bucket Thresholds'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='delay_bucket_thresholds',
            field=models.CharField(default='5, 15, 30, 60', help_text='Comma-separated list of days for pending delay buckets. Example: 5, 15, 30, 60', max_length=100, verbose_name='Pending Delay Bucket Thresholds'),
        ),
    ]
